/*
 *  Génie logiciel - UPSay - UVSQ - Janvier 2016
 */
package uvsq.gl.exo2.IHM;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.LinkedList;
import uvsq.gl.exo2.Entities.Abstract2DShape;
import uvsq.gl.exo2.Entities.CircleDessin;
import uvsq.gl.exo2.Entities.DrawingCanvas;
import uvsq.gl.exo2.Entities.RectangleDessin;
import uvsq.gl.exo2.Entities.SquareDessin;

/**
 * Cette classe est l'interface graphique du projet mais n'est qu'à son stade basique
 * Il présente seulement un exemple de dessin de quelques formes avec la possibilité 
 * de les déplacer par le drag and drop 
 * Fenêtre construit pavec le GUI Builder
 * @author mccstan
 */
public class IHMDrawingCanvas extends javax.swing.JFrame {
    private  static IHMDrawingCanvas INSTANCE;

    /**
     * Creates new form IHMDrawingCanvas
     */
    private IHMDrawingCanvas() {
        initComponents();
        RectangleDessin rectangle;
        SquareDessin carree;
        CircleDessin cercle;
        DrawingCanvas panneau;
        rectangle=new RectangleDessin.Builder()
                .width(300)
                .height(200)
                .position(100, 100)
                .build();
        rectangle.setRGBFillColor(0, 0, 255);
        carree=new SquareDessin.Builder()
                .position(500, 100)
                .side(200)
                .build();
        carree.setRGBFillColor(255, 255, 255);
        cercle=new CircleDessin.Builder()
                .center(900, 200)
                .radius(200)
                .build();
        cercle.setRGBFillColor(255, 0, 0);
        Collection<Abstract2DShape> shapes =new LinkedList<>();
        shapes.add(rectangle);
        shapes.add(carree);
        shapes.add(cercle);
        panneau=new DrawingCanvas.Builder()
                .canvasName("Dessin de test"+LocalDateTime.now())
                .Shapes(shapes)
                .build();
        panneau.setRGBFillColor(105, 105, 105);
        
        new MoveDrawingCanvasMouseAdapter(panneau);
        
        this.getContentPane().add(panneau);
        
        
    }
    
    public static IHMDrawingCanvas getInstance(){
        if(INSTANCE==null){
            INSTANCE=new IHMDrawingCanvas();
        }
        return INSTANCE;
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuBar = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        New = new javax.swing.JMenuItem();
        Open = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        TheHelp = new javax.swing.JMenuItem();
        About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1500, 600));
        setPreferredSize(new java.awt.Dimension(1500, 600));

        File.setText("Fichier");

        New.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        New.setText("Nouveau");
        File.add(New);

        Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        Open.setText("Ouvrir");
        File.add(Open);

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        Exit.setText("Quitter");
        File.add(Exit);

        MenuBar.add(File);

        Help.setText("Aide");

        TheHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        TheHelp.setText("Accéder à l'aide");
        Help.add(TheHelp);

        About.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        About.setText("A propos");
        Help.add(About);

        MenuBar.add(Help);

        setJMenuBar(MenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHMDrawingCanvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHMDrawingCanvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHMDrawingCanvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHMDrawingCanvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            getInstance().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Help;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem New;
    private javax.swing.JMenuItem Open;
    private javax.swing.JMenuItem TheHelp;
    // End of variables declaration//GEN-END:variables
}
